project:
  type: website
  output-dir: docs
  render: 
    - #mp01.qmd
    - #mp02.qmd
    - #mp03.qmd
    - mp04.qmd

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://reallyluckywombat.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: morph
    toc: false

editor:
  mode: source